[package]
name = "fpls_lib"
version = "0.1.1"
authors = ["lgn <792841450@qq.com>"]
edition = "2018"
license = "MIT"
description = "复制文件或文件夹"
repository = "https://github.com/LgnMs/fpls"

[description]